version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: skybound-postgres-minimal
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=skybound_realms_dev
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_minimal_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: skybound-redis-minimal
    ports:
      - "6379:6379"

volumes:
  postgres_minimal_data: