version: '3.8'

services:
  # PostgreSQL database only
  postgres:
    image: postgres:14-alpine
    container_name: skybound-postgres-dev
    restart: unless-stopped
    environment:
      - POSTGRES_DB=skybound_realms_dev
      - POSTGRES_USER=skybound_dev
      - POSTGRES_PASSWORD=dev_password_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U skybound_dev -d skybound_realms_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis cache only
  redis:
    image: redis:7-alpine
    container_name: skybound-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local